baseURL = "https://www.bradreimer.ca/"
title = "Brad Reimer | Schnauzers & Software"
theme = "hugo-story"
defaultContentLanguage = "en"

## Hugo Built-in Features

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

[languages]
    [languages.en]
        label = "English"
        locale = "en-US"
        weight = 1

## Site Parameters

[Params]
    description = "Fletcher and Fibonacci's favorite place on the web"
    logo = "images/banner.jpg"
    favicon = true
	custom_css = ["css/schrody.css"]
	custom_js = ["js/schrody.js"]

[Params.social]
    github = "https://github.com/bradreimer/"
    twitter = "https://twitter.com/bradreimer/"
    instagram = "https://www.instagram.com/breimer/"
    linkedin = "https://www.linkedin.com/in/breimer/"
