baseURL = "https://www.bradreimer.ca/"
title = "Brad Reimer | Schnauzers & Software"
theme = "hugo-story"
defaultContentLanguage = "en"

## Hugo Built-in Features

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

[languages]
    [languages.en]
        label = "English"
        locale = "en-US"
        weight = 1

## Site Parameters

[Params]
    description = "Brad Reimer's web playground for schnauzers, photography, software experiments, and ESP32 projects."
    logo = "images/banner.jpg"
    favicon = true

[Params.social]
    github = "https://github.com/bradreimer/"
    instagram = "https://www.instagram.com/breimer/"
    linkedin = "https://www.linkedin.com/in/breimer/"
