services:
  static-site:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: bradreimer-web-static
    ports:
      - "3000:80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
